### ISSUE TITLE
[Feature] Offline Data Sync

### ISSUE THREAD

**Issue by aritchie** [sthewissen/MVP#10]
What
Ability to read & write new items while offline

Discussion
This will be bringing in dependencies via Shiny.  Will also need some sort of local data storage engine like SQLite.  Branch work has started here: https://github.com/aritchie/MVP/tree/offline/MVP

Let me know your thoughts.

**Comment by sthewissen** [comment]
Sounds great Allan! That's definitely cool to have in there! Would the SQLite local storage just be used to store the offline items queue for now? I assume so in the scope of this, but could also be used in the future to cache past contributions and perhaps user profile data, so SQLite seems like a good way to go.

**Comment by sthewissen** [comment]
Closing this for now. Not because I don't appreciate the effort because I do. Could always bring something like it in, but currently, the app will move forward without it. The number of contributions added without an internet connection will probably not be huge, to begin with, but I'm happy to be proven wrong on it.
